version: "3.7"

services:
  hawkscan:
    image: stackhawk/hawkscan:latest
    environment:
      - API_KEY=${HAWK_API_KEY}
      - APP_ID=830780ac-07be-4995-89d4-0645f1f0e95a
      - APP_ENV=delegated
      - HOST=http://vuln-proxy:8020
    volumes:
      - .:/hawk:delegated

  vuln-proxy:
    logging:
      driver: none

  vuln-django:
    logging:
      driver: none
