name: HawkScan
on:
  push:
  pull_request:
    branches:
      - main
      - master
#  workflow_dispatch:
jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Docker Build
        run: docker-compose build
      - name: Run App
        run: docker-compose up -d
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v1.3.2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          environmentVariables: APP_ENV APP_ID HOST APP_HOST
        env:
          APP_ENV: GitHub
          APP_ID: d023acb5-c8d4-426d-a572-148bfea653b4
          HOST: 'http://localhost:8020'
          APP_HOST: 'http://localhost:8020'
